
const STORAGE='bahiaRoadTripV2';
const CATEGORIES=['Comidas','Actividades','Compras','Seguro','Movilidad adicional','Otros'];
const BASES=[['total','Total fijo'],['person','Por persona'],['day','Por día'],['personDay','Por persona y día']];
const el=id=>document.getElementById(id);const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function uid(){if(window.crypto&&crypto.getRandomValues){const a=new Uint32Array(2);crypto.getRandomValues(a);return[...a].map(n=>n.toString(36)).join('')}return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function iso(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function defaultState(){const s=new Date(),e=new Date();e.setDate(e.getDate()+5);return{origin:'Bariloche',startDate:iso(s),endDate:iso(e),travelers:1,currency:'ARS',contingency:10,fuelConsumption:8.5,fuelPrice:0,usdArs:0,budgetTarget:0,notes:'',stages:[{id:uid(),from:'Bariloche',to:'Bahía Blanca',km:0,localKm:0,tolls:0,parking:0,nights:1,routeMinutes:0,routeHint:''}],stays:[],expenses:[{id:uid(),category:'Comidas',name:'Comidas y bebidas',price:0,basis:'personDay'},{id:uid(),category:'Otros',name:'Otros gastos',price:0,basis:'total'}]}}
function clean(raw){const d=defaultState();if(!raw||typeof raw!=='object')return d;return{origin:String(raw.origin||d.origin),startDate:/^\d{4}-\d{2}-\d{2}$/.test(raw.startDate||'')?raw.startDate:d.startDate,endDate:/^\d{4}-\d{2}-\d{2}$/.test(raw.endDate||'')?raw.endDate:d.endDate,travelers:Math.max(1,Math.round(finite(raw.travelers,1))),currency:raw.currency==='USD'?'USD':'ARS',contingency:Math.min(100,Math.max(0,finite(raw.contingency,10))),fuelConsumption:Math.max(0,finite(raw.fuelConsumption,8.5)),fuelPrice:Math.max(0,finite(raw.fuelPrice,0)),usdArs:Math.max(0,finite(raw.usdArs,0)),budgetTarget:Math.max(0,finite(raw.budgetTarget,0)),notes:String(raw.notes||''),stages:Array.isArray(raw.stages)&&raw.stages.length?raw.stages.map(x=>({id:String(x.id||uid()),from:String(x.from||''),to:String(x.to||''),km:Math.max(0,finite(x.km)),localKm:Math.max(0,finite(x.localKm)),tolls:Math.max(0,finite(x.tolls)),parking:Math.max(0,finite(x.parking)),nights:Math.max(0,Math.round(finite(x.nights))),routeMinutes:Math.max(0,Math.round(finite(x.routeMinutes))),routeHint:String(x.routeHint||'')})):d.stages,stays:Array.isArray(raw.stays)?raw.stays.map(x=>({id:String(x.id||uid()),name:String(x.name||'Alojamiento'),location:String(x.location||''),checkIn:String(x.checkIn||''),checkOut:String(x.checkOut||''),priceTotal:Math.max(0,finite(x.priceTotal)),currency:x.currency==='USD'?'USD':'ARS',include:x.include!==false,ocrHint:String(x.ocrHint||'')})):[],expenses:Array.isArray(raw.expenses)?raw.expenses.map(x=>({id:String(x.id||uid()),category:CATEGORIES.includes(x.category)?x.category:'Otros',name:String(x.name||'Gasto'),price:Math.max(0,finite(x.price)),basis:BASES.some(b=>b[0]===x.basis)?x.basis:'total'})):d.expenses}}
function shared(){if(!location.hash.startsWith('#b='))return null;try{let s=location.hash.slice(3).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return clean(JSON.parse(decodeURIComponent(escape(atob(s)))))}catch{return null}}
function load(){const sh=shared();if(sh)return sh;try{const r=localStorage.getItem(STORAGE);if(r)return clean(JSON.parse(r))}catch{}return defaultState()}let state=load();
const refs={origin:el('origin'),startDate:el('startDate'),endDate:el('endDate'),travelers:el('travelers'),currency:el('currency'),contingency:el('contingency'),fuelConsumption:el('fuelConsumption'),fuelPrice:el('fuelPrice'),usdArs:el('usdArs'),budgetTarget:el('budgetTarget'),notes:el('notes'),stages:el('stages'),stays:el('stays'),expenseBody:el('expenseBody'),status:el('status')};
function days(){const a=new Date(`${state.startDate}T12:00:00`),b=new Date(`${state.endDate}T12:00:00`);let n=Math.round((b-a)/86400000);if(!Number.isFinite(n)||n<0)n=0;return Math.max(1,n+1)}
function nightsBetween(a,b){if(!/^\d{4}-\d{2}-\d{2}$/.test(a)||!/^\d{4}-\d{2}-\d{2}$/.test(b))return 0;return Math.max(0,Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000))}
function convert(v,from){if(from===state.currency)return v;if(!state.usdArs)return 0;return from==='USD'?v*state.usdArs:v/state.usdArs}
function mult(b){return({total:1,person:state.travelers,day:days(),personDay:state.travelers*days()})[b]||1}
function calc(){const routeKm=state.stages.reduce((s,x)=>s+x.km,0),localKm=state.stages.reduce((s,x)=>s+x.localKm,0),driveMinutes=state.stages.reduce((s,x)=>s+(x.routeMinutes||0),0),totalKm=routeKm+localKm,fuelLiters=totalKm*state.fuelConsumption/100,fuelCost=fuelLiters*state.fuelPrice,tolls=state.stages.reduce((s,x)=>s+x.tolls,0),parking=state.stages.reduce((s,x)=>s+x.parking,0),car=fuelCost+tolls+parking;const stays=state.stays.filter(x=>x.include).reduce((s,x)=>s+convert(x.priceTotal,x.currency),0),reservedNights=state.stays.filter(x=>x.include).reduce((s,x)=>s+nightsBetween(x.checkIn,x.checkOut),0),otherRows=state.expenses.map(x=>({...x,subtotal:x.price*mult(x.basis)})),other=otherRows.reduce((s,x)=>s+x.subtotal,0),base=car+stays+other,cont=base*state.contingency/100,total=base+cont;return{routeKm,localKm,driveMinutes,totalKm,fuelLiters,fuelCost,tolls,parking,car,stays,reservedNights,otherRows,other,base,cont,total}}
function money(v){return new Intl.NumberFormat('es-AR',{style:'currency',currency:state.currency,maximumFractionDigits:state.currency==='ARS'?0:2}).format(finite(v))}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
function flash(t){refs.status.textContent=t;clearTimeout(flash.t);flash.t=setTimeout(()=>refs.status.textContent='',3000)}
function mapsUrl(from,to){return`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(from)}&destination=${encodeURIComponent(to)}&travelmode=driving`}
function wholeRouteUrl(){const valid=state.stages.filter(x=>x.from.trim()&&x.to.trim());if(!valid.length)return mapsUrl(state.origin,'Bahía Blanca');const origin=valid[0].from,destination=valid[valid.length-1].to,points=valid.slice(0,-1).map(x=>x.to).filter(Boolean);let url=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=driving`;if(points.length)url+=`&waypoints=${encodeURIComponent(points.join('|'))}`;return url}
const GEO_CACHE_KEY='bahiaGeoCacheV1';let geoCache={};try{geoCache=JSON.parse(localStorage.getItem(GEO_CACHE_KEY)||'{}')||{}}catch{}let nextGeoAt=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));function saveGeoCache(){try{localStorage.setItem(GEO_CACHE_KEY,JSON.stringify(geoCache))}catch{}}function routeTimeText(mins){mins=Math.max(0,Math.round(finite(mins)));if(!mins)return'0 h';const h=Math.floor(mins/60),m=mins%60;return h?`${h} h${m?` ${m} min`:''}`:`${m} min`}async function geocodePlace(query){const raw=String(query||'').trim();if(!raw)throw new Error('Falta una ubicación');const key=raw.toLocaleLowerCase('es');if(geoCache[key])return geoCache[key];const wait=Math.max(0,nextGeoAt-Date.now());if(wait)await sleep(wait);nextGeoAt=Date.now()+1100;const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=ar&q=${encodeURIComponent(raw+', Argentina')}`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('No pude localizar '+raw);const data=await res.json();if(!data?.length)throw new Error('No encontré '+raw+' en OpenStreetMap');const out={lat:Number(data[0].lat),lon:Number(data[0].lon),name:data[0].display_name||raw};geoCache[key]=out;saveGeoCache();return out}async function osrmRoute(a,b){const url=`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=false&steps=false&alternatives=false`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('El motor de rutas no respondió');const data=await res.json();const r=data?.routes?.[0];if(data?.code!=='Ok'||!r)throw new Error('No encontré una ruta vial entre esos puntos');return{km:r.distance/1000,minutes:r.duration/60}}async function calculateStageRoute(stage){if(!stage.from.trim()||!stage.to.trim())throw new Error('Completá origen y destino');stage.routeHint='Buscando ubicaciones…';renderStages();const a=await geocodePlace(stage.from),b=await geocodePlace(stage.to);stage.routeHint='Calculando ruta vial…';renderStages();const r=await osrmRoute(a,b);stage.km=Math.round(r.km*10)/10;stage.routeMinutes=Math.round(r.minutes);stage.routeHint=`Automático · ${routeTimeText(stage.routeMinutes)}`;save();return r}