let undoAction=null,undoTimer=null;
function offerUndo(message,action){undoAction=action;clearTimeout(undoTimer);el('undoText').textContent=message;el('undoToast').hidden=false;undoTimer=setTimeout(()=>{el('undoToast').hidden=true;undoAction=null},6500)}
el('undoBtn').addEventListener('click',()=>{if(undoAction){const action=undoAction;undoAction=null;clearTimeout(undoTimer);el('undoToast').hidden=true;action();flash('Acción deshecha')}});

refs.stages.addEventListener('input',onStage);refs.stages.addEventListener('change',onStage);
refs.stages.addEventListener('click',async e=>{
  const card=e.target.closest('[data-stage]');if(!card)return;const x=state.stages.find(v=>v.id===card.dataset.stage);if(!x)return;const idx=state.stages.findIndex(v=>v.id===x.id);
  if(e.target.classList.contains('map-stage')){window.open(mapsUrl(x.from,x.to),'_blank','noopener');return}
  if(e.target.classList.contains('move-up')&&idx>0){[state.stages[idx-1],state.stages[idx]]=[state.stages[idx],state.stages[idx-1]];renderStages();renderTotals();return}
  if(e.target.classList.contains('move-down')&&idx<state.stages.length-1){[state.stages[idx+1],state.stages[idx]]=[state.stages[idx],state.stages[idx+1]];renderStages();renderTotals();return}
  if(e.target.classList.contains('calc-stage')){
    const b=e.target;b.disabled=true;b.textContent='Calculando…';
    try{await calculateStageRoute(x);flash(`Etapa calculada: ${x.km.toLocaleString('es-AR')} km · ${routeTimeText(x.routeMinutes)}`)}
    catch(err){x.routeHint='Error · '+(err?.message||'No se pudo calcular');flash(x.routeHint)}
    finally{renderStages();renderTotals()}return
  }
  if(e.target.classList.contains('remove-stage')){
    if(state.stages.length===1){flash('El viaje necesita al menos una etapa.');return}
    const removed={...x};state.stages.splice(idx,1);renderStages();renderTotals();offerUndo('Etapa eliminada',()=>{state.stages.splice(idx,0,removed);renderStages();renderTotals()});return
  }
});

function onStage(e){
  const card=e.target.closest('[data-stage]');if(!card)return;const x=state.stages.find(v=>v.id===card.dataset.stage);if(!x)return;const idx=state.stages.findIndex(v=>v.id===x.id);
  if(e.target.classList.contains('s-from')){const old=x.from;x.from=e.target.value;x.routeMinutes=0;x.routeHint='Origen modificado · recalculá la ruta';if(idx===0){state.origin=x.from;refs.origin.value=x.from}else if(state.stages[idx-1]&&state.stages[idx-1].to===old)state.stages[idx-1].to=x.from}
  if(e.target.classList.contains('s-to')){const old=x.to;x.to=e.target.value;x.routeMinutes=0;x.routeHint='Destino modificado · recalculá la ruta';const next=state.stages[idx+1];if(next&&(!next.from||next.from===old))next.from=x.to}
  if(e.target.classList.contains('s-km')){x.km=Math.max(0,finite(e.target.value));x.routeHint='Km editados manualmente';x.routeMinutes=0}
  if(e.target.classList.contains('s-local'))x.localKm=Math.max(0,finite(e.target.value));if(e.target.classList.contains('s-tolls'))x.tolls=Math.max(0,finite(e.target.value));if(e.target.classList.contains('s-parking'))x.parking=Math.max(0,finite(e.target.value));if(e.target.classList.contains('s-nights'))x.nights=Math.max(0,Math.round(finite(e.target.value)));
  renderTotals()
}

el('addStageBtn').addEventListener('click',()=>{const prev=state.stages[state.stages.length-1];state.stages.push({id:uid(),from:prev?.to||'',to:'',km:0,localKm:0,tolls:0,parking:0,nights:0,routeMinutes:0,routeHint:''});renderStages();renderTotals();requestAnimationFrame(()=>{const last=refs.stages.querySelector('.stage-card:last-child');last?.scrollIntoView({behavior:'smooth',block:'center'});last?.querySelector('.s-to')?.focus()})});
el('addReturnBtn').addEventListener('click',()=>{const first=state.stages[0],last=state.stages[state.stages.length-1];if(!first||!last)return;const home=first.from||state.origin;if(last.to.trim().toLocaleLowerCase('es')===home.trim().toLocaleLowerCase('es')){flash('La última etapa ya termina en el origen inicial.');return}state.stages.push({id:uid(),from:last.to||'',to:home,km:0,localKm:0,tolls:0,parking:0,nights:0,routeMinutes:0,routeHint:'Regreso agregado · calculá la ruta'});renderStages();renderTotals();requestAnimationFrame(()=>refs.stages.querySelector('.stage-card:last-child')?.scrollIntoView({behavior:'smooth',block:'center'}))});
el('calcAllRoutesBtn').addEventListener('click',async()=>{const b=el('calcAllRoutesBtn');b.disabled=true;const original=b.textContent;let ok=0;try{for(let i=0;i<state.stages.length;i++){const x=state.stages[i];b.textContent=`Calculando ${i+1}/${state.stages.length}…`;refs.status.textContent=`Calculando etapa ${i+1} de ${state.stages.length}…`;try{await calculateStageRoute(x);ok++}catch(err){x.routeHint='Error · '+(err?.message||'No se pudo calcular')}renderStages();renderTotals();await sleep(250)}flash(`${ok} de ${state.stages.length} etapas calculadas`)}finally{b.disabled=false;b.textContent=original}});
el('wholeRouteBtn').addEventListener('click',()=>window.open(wholeRouteUrl(),'_blank','noopener'));

refs.stays.addEventListener('input',onStay);refs.stays.addEventListener('change',async e=>{onStay(e);if(e.target.classList.contains('h-photo')&&e.target.files?.[0])await runOcr(e.target.closest('[data-stay]').dataset.stay,e.target.files[0])});
refs.stays.addEventListener('click',e=>{const card=e.target.closest('[data-stay]');if(card&&e.target.classList.contains('remove-stay')){const idx=state.stays.findIndex(v=>v.id===card.dataset.stay);if(idx<0)return;const removed={...state.stays[idx]};state.stays.splice(idx,1);renderStays();renderTotals();offerUndo('Estadía eliminada',()=>{state.stays.splice(idx,0,removed);renderStays();renderTotals()})}});
function onStay(e){const card=e.target.closest('[data-stay]');if(!card)return;const x=state.stays.find(v=>v.id===card.dataset.stay);if(!x)return;if(e.target.classList.contains('h-name'))x.name=e.target.value;if(e.target.classList.contains('h-location'))x.location=e.target.value;if(e.target.classList.contains('h-in')){x.checkIn=e.target.value;if(!x.checkOut&&x.checkIn){const d=new Date(`${x.checkIn}T12:00:00`);d.setDate(d.getDate()+1);x.checkOut=iso(d);renderStays()}}if(e.target.classList.contains('h-out'))x.checkOut=e.target.value;if(e.target.classList.contains('h-price'))x.priceTotal=Math.max(0,finite(e.target.value));if(e.target.classList.contains('h-currency'))x.currency=e.target.value;if(e.target.classList.contains('h-include'))x.include=e.target.checked;renderTotals()}
el('addStayBtn').addEventListener('click',()=>{const last=state.stays[state.stays.length-1];state.stays.push({id:uid(),name:'Alojamiento',location:last?.location||'',checkIn:last?.checkOut||'',checkOut:'',priceTotal:0,currency:state.currency,include:true,ocrHint:''});renderStays();renderTotals();requestAnimationFrame(()=>{const card=refs.stays.querySelector('.stay-card:last-child');card?.scrollIntoView({behavior:'smooth',block:'center'});card?.querySelector('.h-name')?.select()})});

let tessPromise=null;function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(tessPromise)return tessPromise;tessPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=()=>resolve(window.Tesseract);s.onerror=()=>reject(new Error('No se pudo cargar OCR'));document.head.appendChild(s)});return tessPromise}
function parseMoneyText(text){const lines=text.split(/\n+/).map(s=>s.trim()).filter(Boolean);const candidates=[];function num(s){s=s.replace(/\s/g,'');if(s.includes(',')&&s.includes('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');else{const parts=s.split('.');if(parts.length>2||parts.at(-1)?.length===3)s=s.replace(/\./g,'')}return finite(s,0)}for(const line of lines){const priority=/total|importe|precio final|a pagar|final/i.test(line)?2:1;const currency=/\bUSD\b|US\$/i.test(line)?'USD':/\bARS\b|\$/i.test(line)?'ARS':null;const re=/(?:US\$|USD|ARS|\$)\s*([0-9][0-9.,\s]*)/gi;let m;while((m=re.exec(line)))candidates.push({value:num(m[1]),currency,priority,line})}if(!candidates.length)return null;candidates.sort((a,b)=>(b.priority-a.priority)||(b.value-a.value));return candidates[0]}
async function runOcr(stayId,file){const x=state.stays.find(v=>v.id===stayId);if(!x)return;x.ocrHint='Leyendo captura…';renderStays();try{const T=await loadTesseract();const worker=await T.createWorker('spa+eng',1,{logger:m=>{if(m.status==='recognizing text'){x.ocrHint=`Leyendo captura… ${Math.round((m.progress||0)*100)}%`;const n=document.querySelector(`[data-stay="${CSS.escape(stayId)}"] .ocr-status`);if(n)n.textContent=x.ocrHint}}});const out=await worker.recognize(file);await worker.terminate();const hit=parseMoneyText(out.data.text||'');if(hit&&hit.value>0){x.priceTotal=hit.value;x.currency=hit.currency||x.currency;x.ocrHint=`OCR sugirió ${hit.currency||x.currency} ${hit.value.toLocaleString('es-AR')}. Revisá el importe detectado.`;flash('Precio detectado. Revisalo antes de continuar.')}else x.ocrHint='OCR completado: no pude identificar un importe con suficiente claridad.';renderStays();renderTotals()}catch(err){x.ocrHint='No se pudo procesar la captura. Podés cargar el importe manualmente.';renderStays();renderTotals()}}

refs.expenseBody.addEventListener('input',onExpense);refs.expenseBody.addEventListener('change',onExpense);refs.expenseBody.addEventListener('click',e=>{const row=e.target.closest('[data-expense]');if(row&&e.target.classList.contains('remove-expense')){const idx=state.expenses.findIndex(v=>v.id===row.dataset.expense);if(idx<0)return;const removed={...state.expenses[idx]};state.expenses.splice(idx,1);renderExpenses();renderTotals();offerUndo('Gasto eliminado',()=>{state.expenses.splice(idx,0,removed);renderExpenses();renderTotals()})}});
function onExpense(e){const row=e.target.closest('[data-expense]');if(!row)return;const x=state.expenses.find(v=>v.id===row.dataset.expense);if(!x)return;if(e.target.classList.contains('e-cat'))x.category=e.target.value;if(e.target.classList.contains('e-name'))x.name=e.target.value;if(e.target.classList.contains('e-price'))x.price=Math.max(0,finite(e.target.value));if(e.target.classList.contains('e-basis'))x.basis=e.target.value;renderTotals()}
el('addExpenseBtn').addEventListener('click',()=>{state.expenses.push({id:uid(),category:'Otros',name:'Nuevo gasto',price:0,basis:'total'});renderExpenses();renderTotals();requestAnimationFrame(()=>{const row=refs.expenseBody.querySelector('tr:last-child');row?.scrollIntoView({behavior:'smooth',block:'center'});row?.querySelector('.e-name')?.select()})});

el('shareBtn').addEventListener('click',async()=>{const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(state)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=`${location.origin}${location.pathname}#b=${encoded}`;try{await navigator.clipboard.writeText(url);flash('Enlace compartible copiado')}catch{prompt('Copiá este enlace:',url)}});
el('printBtn').addEventListener('click',()=>window.print());
el('resetBtn').addEventListener('click',()=>{if(!confirm('¿Reiniciar toda la planificación?'))return;state=defaultState();history.replaceState(null,'',location.pathname+location.search);boot();flash('Planificación reiniciada')});
el('exportBtn').addEventListener('click',()=>{const c=calc();const q=v=>{const s=String(v??'');return/[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};const rows=[['Viaje a Bahía Blanca'],['Salida',state.startDate],['Regreso',state.endDate],['Viajeros',state.travelers],[],['ETAPAS'],['Desde','Hasta','Km ruta','Tiempo conducción (min)','Km locales','Peajes','Estacionamiento'],...state.stages.map(x=>[x.from,x.to,x.km,x.routeMinutes||0,x.localKm,x.tolls,x.parking]),[],['ESTADÍAS'],['Alojamiento','Localidad','Check-in','Check-out','Precio','Moneda','Incluida'],...state.stays.map(x=>[x.name,x.location,x.checkIn,x.checkOut,x.priceTotal,x.currency,x.include?'Sí':'No']),[],['RESUMEN'],['Km totales',c.totalKm],['Combustible litros',c.fuelLiters],['Costo auto',c.car],['Alojamientos',c.stays],['Otros',c.other],['Contingencia',c.cont],['TOTAL',c.total]];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='viaje-bahia-blanca.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);flash('CSV exportado')});

function boot(){setConfig();renderStages();renderStays();renderExpenses();renderTotals()}boot();if(location.hash.startsWith('#b='))flash('Planificación compartida cargada');
